puppylinux-woof-CE/woof-CE

woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh

These echo commands seem to be a leftover of KRG's testing session. They unnecessarily clutter console output when using petget in a text console.

Delete unnecessary echo commands

---

woof-code/rootfs-skeleton/usr/sbin/fixmenus

A fix to not display in main menu, categories commented in /etc/xdg/templates/_root_.jwmrc
See http://woof-ce.26403.n7.nabble.com/fixmenus-categories-displayed-in-main-menu-td743.html

fixmenus: to not display commented categories

---

woof-code/rootfs-skeleton/usr/sbin/filemnt

The script behaves as usual, but it can also be used to mount
and unmount whatever is supported by the mount utility.
sh-4.3# mv freedos10.img freedos10.vfat
sh-4.3# filemnt ${PWD}/freedos10.vfat
Mount: /mnt/home/freedos10.vfat
sh-4.3# filemnt ${PWD}/freedos10.vfat
UnMount: /mnt/home/freedos10.vfat

/usr/sbin/filemnt: the file extension is actually the mount type.

---

woof-code/rootfs-skeleton/usr/lib/gtkdialog/svg_bar

adding 'bold' to the text line greatly improves the readability of text in pmount and other apps using svg_bar

improve readability of svg_bar text

---

woof-code/boot/initrd-tree0/init

The cleanup commit simply changes the code to consistently use {} around variable names.
The fix commit relates to code that backs-out of updating a save-file/folder to do pupmode=5. This code was missed in all previous save-folder patches.

Cleanup and fix a missed bit in the save-folder code in "init"

---

woof-code/rootfs-skeleton/usr/sbin/icon_switcher

the 'more themes' button was pointing to gtk themes exchange rather than icon themes exchange

fixed wrong link to forum

---

woof-code/rootfs-skeleton/usr/bin/pman
woof-code/rootfs-skeleton/usr/local/petget/service_pack.sh
woof-code/rootfs-skeleton/usr/local/video_upgrade/video_upgrade_wizard
woof-code/rootfs-skeleton/usr/sbin/check_internet
woof-code/rootfs-skeleton/usr/sbin/ipinfo

I don't like the fact Puppy "phones home", for two reasons:
- Security - if you have the ability to capture the traffic of a Linux machine, it's easy to identify Puppy. As fingerprinting is one of the first steps an attacker performs (for example, when trying to find an exploit that works against a remote Linux machine), we want to make it harder. However, this ping call is our way to test a network connection, so we have to keep it.
- Privacy - using a different site (that is known to respect the user's privacy, unlike Google) is all we can do to improve privacy in this respect.
@01micko @mavrothal Is there any additional anti-privacy feature that most users don't use? If yes, we should disable it by default.

Extra privacy

---

woof-code/boot/boot-dialog/help2.msg
woof-code/huge_extras/init

This facility provides a workaround when the keyboard does not work during the 'init' script because a kernel module is not available yet.
The module files to 'insmod' can be specified as either a 'pimod' kernel parameter, or the first line of the text file '/mnt/data${PSUBDIR}/${DISTRO_FILE_PREFIX}_${KERNELVER}_init_modules.txt'

Implement an 'insmod' facility in 'init' script

---

woof-code/rootfs-skeleton/usr/sbin/fixmenus

This was
EXECMENU="`echo -n "$ONELINE" | grep -o '^PUPPYMENU.*' | cut -f 2-5 -d ' '`"
Then it became
if [[ "$ONELINE" == PUPPYMENU* ]] ; then
read -r one two three four five <<< "$ONELINE"
EXECMENU="$two $three $four $five"
fi
Which is basically the same, but I forgot to add 'six <<<' to make it behave exactly as cut -f 2-5 -d
But I see that this 'cut -f 2-5' is actually *not* needed.

fixmenus: shorten code

---

woof-code/huge_extras/init

Specifying the module list by a config file, should behave the same way as specifying the module list by kernel parameter, when handling a different kernel version.
This patch removes the kernel version from the config filename.

init insmod facility - fix config filename

---

woof-code/rootfs-skeleton/sbin/probepart

if vercmp $COREUTILSVER le 6.12;then
sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sda sdb sr0
else
sda sda1 sda2 sda3 sda4 sdb sdb1 sdb2 sdb3 sdb4 sr0
fi
New approach
sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sr0
bash
ALLDEVS=$(
for dev in ${PARTNAMES} ${ALLDRVS} ; do
[[ $dev != sd[a-z] ]] && echo $dev
done
)

probepart: dot not check sort version, replace code

---

woof-code/huge_extras/init
woof-code/huge_extras/initmodules
woof-code/rootfs-skeleton/usr/sbin/bootmanager

These patches enable the "init insmod facilty" config file to work when 'psavemark' is specified.

init insmod facility - support psavemark

---

woof-code/huge_extras/init
woof-code/huge_extras/initmodules
woof-code/rootfs-skeleton/usr/sbin/bootmanager

'init' now uses the ZDRV variable to decide when to act, and to access the found zdrv...sfs.
'initmodules' and 'bootmanager' now use PDEV1 to find the 'initrd.gz' file.

init insmod facility - improve finding files

---

woof-code/huge_extras/initmodules

This adds detection of a CD/DVD boot and provides an explanation message if it can't work with the current setup.
I also adds the standard bootmanager error message if there is no savefile/savefolder defined yet.

init insmod modules - initmodules - add extra error messages

---

woof-code/rootfs-skeleton/usr/sbin/puppyapps

This implements the same behavior as before and fixes possible issues in default*)
All switches seem to work as before, no problems so far.
default*)
I have tested this in command line, rox and pcmanfm and passes the test in all of them.
tested apps: defaultaudioplayer, defaultmediaplayer
The previous method worked randomly, some files with long names and/or unusual chars failed to open. In fact it wasn't working at all in pcmanfm.
Now any file or multiple files passed through puppyapps work perfectly and really works like a wrapper.
I added exec in the same script because some apps might expect the app to terminate when the job is done, making it a wrapper indeed.

puppyapps: simplify command line parsing

---

woof-code/rootfs-skeleton/usr/sbin/updatenetmoduleslist.sh

These changes produce the same results, the diffs show very few minimal differences here and there in the description.
$KERNSUBVER and $KERNMAJVER are not used in the script.. commented out
time updatenetmoduleslist.sh
real    0m38.100s
user    0m5.426s
sys 0m15.572s
time ./updatenetmoduleslist.sh
real    0m19.570s
user    0m1.780s
sys 0m3.886s

make updatenetmoduleslist.sh a bit faster

---

woof-code/huge_extras/init

Always look in the zdrv partition for the config file first.
When 'savemark' is active, performance can be improved by copying the config file to be beside the zdrv...sfs, instead of beside the savefile/savefolder. This avoids an extra mount of the savefile/savefolder partition.

initmodules - look in zdrv partition first

---

woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
woof-code/rootfs-skeleton/etc/rc.d/rc.update

If kmod is there, then busybox depmod  is not used at all
However busybox depmod has a higher priority than depmod itself.
If I remember correctly, depmod was a symlink to busybox in older versions,
so it makes sense to use depmod as is.
Besides, it seems that busybox needs to be patched for the depmod applet to work with puppy?
I wrote something about this a long time ago:
http://murga-linux.com/puppy/viewtopic.php?t=99162

rc.update/sysinit: use busybox depmod as a last resort

---

woof-code/rootfs-skeleton/usr/sbin/alsaconf

that is more noticeable in slow pcs
build_card_db
(original)
real    0m30.079s
user    0m5.343s
sys 0m15.482s
(mod)
real    0m5.384s
user    0m0.747s
sys 0m1.197s

alsaconf: minor speedup

---

woof-code/rootfs-skeleton/etc/init.d/10alsa

The script assumes there is always a space after 0
snd_via82xx            14561  0[extra space]
The I've encountered a case where that is not true...
snd_via82xx            14561  0
--

10alsa stop: change grep '0 $' to grep -E '0 $|0$'

---

woof-code/rootfs-skeleton/usr/sbin/xorgwizard-automatic

ddcprobe just hangs in some distros and hardware (Tahr64 in a MacBookPro in my case) and then the X startup (xwin) as well as xorgwizard{,-automatic,-cli} all freeze. Upon inactivation X proceeds straight to Desktop!
Not sure if such an irreversible measure is wise, or should go through the hassle to test in every script that uses ddcprobe and revert at the script exit. 
Given that we move away from xorgwizard is probably an overkill.
Please review. (Also the code could be improved.)

Inactivate ddcprobe if broken. Freezes X startup

---

woof-code/huge_extras/init

Trim any residual end-of-line characters from config file line.
The config file can be a dos file or inside an iso, and still work.

initmodules - trim config file line

---

woof-code/huge_extras/init

Currently, if a SAVEMARK file or psavemark boot parameter is being utilised, and pmedia and pdev1 boot parameters are specified, the psavemark partition is ignored.
This patch ensures that even if pmedia and pdev1 are specified, the psavemark partition remains in the search list.
A save partition specified by a SAVEMARK file only, will still be ignored, but the addition of a psavemark boot parameter will restore the save partition to the search list.

enable psavemark to work with pmedia and psave

---

woof-code/rootfs-skeleton/etc/init.d/10alsa

These changes allow the user to check 10alsa's output in
/tmp/services/10alsa.start.log and /tmp/services/10alsa.stop.log
It also checks for /dev/mixer a little longer if necessary.

10alsa: various edits

---

woof-code/rootfs-skeleton/usr/lib/gtkdialog/xml_info

xml_info always produces the same /tmp/xml_info.svg
when you want a red or pink xml_info.svg
. /usr/lib/gtkdialog/xml_info gtk red
it doesn't work..
These changes makes it behave properly..

xml_info: bugfix

---

woof-code/rootfs-skeleton/usr/lib/gtkdialog/box_splash

busybox ps: the less digits a pid has, the more leading spaces will be
1 root       0:01 /bin/busybox init
635 root       0:00 /tmp/yaf-splash --class=gtkdialog-splash ...
1172 root       0:00 grep yaf
30053 root       0:00 /bin/bash
solution:  convert multiple spaces to one space

box_splash: bugfix

---

woof-code/rootfs-skeleton/etc/modprobe.d/alsa-base.conf

This fixes a common issue reported many times over the years..

alsa-base.conf: Keep HDA HDMI from being loaded as first soundcard

---

woof-code/huge_extras/initmodules

A complete rewrite.
It now determines the modules that need to be loaded in "init", including dependencies, by examining the modules that are loaded in the current running system.
Executed with a "-q" parameter, it displays nothing, but writes a config file if needed, and if it can.
Otherwise it is a GUI utility that displays informative messages and it's list of needed modules. The list can then be modified or accepted as is.

initmodules - automatically determine needed modules

---

woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown
woof-code/rootfs-skeleton/usr/sbin/quicksetup

These patches enable first boot to create an initmodules config file and for first shutdown to copy any initmodules config file found in /tmp into the same directory as the save layer.
(mavrothal is the real author of the quicksetup patch.)

Add initmodules support for first boot and first shutdown

---

woof-code/huge_extras/init

Unfortunately my original version of this patch was the wrong code.
Both versions work, but this makes the code correspond to that agreed in the forum.

fix psavemark to work with pmedia and psave code

---

woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns

This helps identifying the correct network.
ex: when the SSID is hidden (#756)
To make room, the 'Strength: XX/XX' string has been removed,
there is already a nice image...

SNS: show Access Point MAC address

---

woof-code/0setup

otherwise /usr/local/petget/* to update dbs in a running pup
the files in ./support are supposed to be always the latest version

0setup: use ./support debdb2pupdb|find_cat if building from woof

---

woof-code/rootfs-skeleton/usr/sbin/connectwizard
woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd
woof-code/rootfs-skeleton/usr/sbin/get_modem_alternate_device

These changes support new APIs of the frisbee-1.4 and pgprs-2.0 packages.  They are invoked by the commands, frisbee and pgprs.  They take a single argument for a specific action.  The connectwizard scripts will use them if present.  If an older version of frisbee is installed, the old interface is used.  For pgprs, only the new package is supported, because the old version should be removed from woof-CE and a new pgprs package option added to woof-CE.
Although the results from get_modem_alternate_device omit an argument-specified device name, the new option requests that all found devices be returned, as needed by the new frisbee and pgprs.

Use new APIs for frisbee-1.4 and pgprs-2.0; add get...devices 'ALL' option

---

woof-code/rootfs-packages/frisbee/pinstall.sh

Avoid 2 messages re file not found for sed operation, during build. Close #780 
Checks for file existence before editing, in 3 places.

Correct frisbee pinstall script to avoid file-not-found messages

---

woof-code/boot/initrd-tree0/init

This makes fdrv like other drv files, if "init" finds an fdrv file, it gets loaded into the aufs stack.
No extra "pfix=" boot parameter is required.

fdrv - remove EXTRAFW conditionals and pfix=fw_drv

---

woof-code/boot/initrd-tree0/init

This is not one of the patches I intimated earlier.
It's a small patch to improve the robustness of the code against an "initrd.gz" that's missing any mountpoint directories.
I found this problem when testing this "init" in tahrpup 6.0.5, if doesn't contain a mountpoint for fdrv.
With this patch, just adding "init" to the "initrd.gz" in Tahrpup 6.0.5 enables a specidied fdrv to be loaded.

sfs's - conditionally create mountpoint directories

---

woof-code/boot/initrd-tree0/init

This patch enables specifications like "adrv=:pcmanfm.sfs" to work.
If "pupsfs=sdc2" is specified then "adrv=:pcmanfm.sfs" is equivalent to "adrv=sdc2:pcmanfm.sfs"

sfs's - make "pupsfs=" partition sticky

---

woof-code/boot/initrd-tree0/init
woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown
woof-code/rootfs-skeleton/usr/sbin/shutdownconfig

These should be the last in this series.
With these patches shutdownconfig will honour the partition specified with "psave=".
They also stop a SAVEMARK file being written if "psave=" is specified, because with "psave=" the partition could be on a different device. e.g. frugal install on SSD, savefolder on HD.
But, why is there SAVEMARK writing code in both shutdownconfig and rc.shutdown?

Rationalise - provide support for "psave=" boot parameter to shutdownconfig

---

woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
woof-code/rootfs-skeleton/usr/local/apps/Connect/AppRun

AppRun was left out of the interface updates related to connectwizard.
Rc.sysinit is updated to support USB3 driver module and to check for frisbee as the active network manager.
AppRun requires execute permission, but rc.sysinit does not.

Update AppRun and rc.sysinit

---

woof-code/rootfs-packages/pgprs/var/log/packages/pgprs-2.0-1

I believe the log/packages files are an old artifact from slacko.  Please correct me if they are somehow necessary in woof.

Delete /var/log/packages/pgprs-2.0-1 - unnecessary

---

woof-code/3builddistro-Z

When doing a cross-build of slacko64-14.2 (target x86-64) using slacko-14.1 (host x86) I notice 1000 errors on this line because "Puppy Standard" directory has a space in it: http://oi65.tinypic.com/351x45d.jpg  (line 967 rationalise = line 1195 testing) and most icons in puppy do not display as consequence. Adding "" around it fixes it and cross-build is a success! :)

Cross-build fix

---

woof-code/rootfs-packages/pmusic/usr/local/pmusic/func_trackinfo

Fixes all instances instead of only the first - ref PR #830

Update remasterpup2: change 5 greps for free space calculation

---

woof-code/rootfs-skeleton/usr/sbin/sfs_load

This is a fudge so that the "init" script doesn't have to handle extra sfs's in LASTUNIONRECORD.
Part of separating responsibility of sfs's:
init handles puppy...sfs, fdrv, zdrv, ydrv, adrv
sfs_load handles all extra sfs's

remove extra sfs's from LASTUNIONRECORD on shutdown

---

woof-code/rootfs-skeleton/usr/local/petget/help.htm

Is linking to old version wise? Or maybe creating a newer info page on puppylinux.com would be more appropriate? :octocat:

Dead link in PPM help

---

woof-code/rootfs-skeleton/usr/bin/dir2pet

The pet.specs values were not being propagated to new pets.  Argument parsing seemed overly complicated and nonintuitive.  Edited parsing for more standard appearance.
Compression default was inconsistent, in that the xz value was used despite the help output stating 'gz' and 'gz' was used if the 'skip' option was set.  Now, the "comp" variable is used everywhere, with its value being overridden as 'gz' for the "arm" architecture.  It is now set to 'gz'.

dir2pet: pet.specs path; argument parsing; help output; compression default

---

woof-code/rootfs-packages/frisbee/pet.specs
woof-code/rootfs-packages/frisbee/usr/local/bin/frisbee
woof-code/rootfs-packages/frisbee/usr/local/frisbee/func

Places SSID of open networks in same column as for encrypted networks.

frisbee: correct formatting of scan results for open networks

---

woof-code/rootfs-skeleton/usr/sbin/remove_builtin

pburn contains a link named "Burn with pBurn" that links to a directory and is not removed when the pburn package gets removed.  If the name lacked spaces, the removal would treat the link as it does for directories and would not remove it because the target directory is not empty (unless the directory is already deleted).  The fix supports spaces in all names and deletes the link.

remove_builtin: fix handling of directory links & names with spaces

---

woof-code/rootfs-skeleton/usr/lib/gtkdialog/xml_button-icon

If the user uses STOCK=puppy and no Puppy Icon Theme (old style), gtk-yes icon is still not found (Re: https://github.com/puppylinux-woof-CE/woof-CE/commit/ffe9957d609d48c2dafa046bcd4e8ceaddd275f4 ). In this scenario always falling back to gtk works better than a double fallback to non-existent puppy image and no find is needed.

fix for STOCK=puppy

---

woof-code/rootfs-skeleton/usr/sbin/xorgwizard

If the user uses xrandr to change resolution, sometimes magic is needed for xorg changes to stick. Feel free to push and adjust better. I also change xorg icon to the most appropriate one and for better variety (do you agree? :D )

xrandr and xorg compatibility fix

---

woof-code/3builddistro-Z

Allows packages-${DISTRO_FILE_PREFIX} to be a symlink so that it can be shared between multiple builds

Allow symlinks in build a .pet with all builtin files

---

woof-code/3builddistro-Z

Rox was a LxPup only feature which is now redundant with the advent of roxfiler so it's creation can be deleted from 3builddistro

Remove Rox link creation

---

merge2out

Uses merge2out to overlay packages-templates, rootfs-packages and
rootfs-skeleton with files from woof-distro.

Add support for copying more things from woof-distro

---

merge2out

Uses merge2out to apply patches from
woof-distro/TARGETARCH/COMPATDISTRO/COMPATVERSION/patches
I also have an edited version of mavrothal's patch-generator.sh at  
https://github.com/woodenshoe-wi/woof-tools
If puppylinux-woof-CE wants to fork woof-tools let me know and I will delete it afterwards, that should make puppylinux-woof-CE the owner of woof-tools.

Add support for applying patches in merge2out

---

woof-distro/arm/raspbian/jessie/DISTRO_PKGS_SPECS-raspbian-jessie
woof-distro/arm/raspbian/jessie/DISTRO_SPECS
woof-distro/arm/raspbian/jessie/patches/no-delete-brcm_pi3.patch

Add firmware for Pi3 wifi.
raspbian/jessie/patches/no-delete-brcm_pi3.patch is only needed
for raspberry pi builds because they do not have a z drive.
I did a test build and everything seems to work fine with xorg_base_new except I can no longer CTRL+ALT+BACKSPACE to exit X.  I can still CTRL+ALT+F2 to get to the command line so it is not a problem if this is intentional, but /etc/X11/xorg.conf still has `Option "DontZap" "false"`

Update raspbian/jessie to 6.0.4

---

woof-distro/arm/raspbian/jessie/DISTRO_PKGS_SPECS-raspbian-jessie
woof-distro/arm/raspbian/jessie/DISTRO_SPECS

Since /lib/firmware is not deleted for arm builds now,
Add firmware debs for USB wifi adapters.
I did discover a problem with loading firmware from /lib/modules/all-firmware when using two different kernels.  On the first boot /etc/modules/firmware.dep gets renamed to firmware.dep._kernel-version_.  When the SD card is booted in a Pi that needs the other kernel version there is no firmware.dep file to rename and /sbin/pup-event-backend-modprobe can't find firmware.dep._kernel-version_ for the other kernel.
I don't know if the best solution is to copy firmware.dep instead of renaming it or to move the Pi3 wifi firmware to /lib/firmware and give up on using /lib/modules/all-firmware for arm builds.

Update raspbian/jessie to 6.0.5

---

woof-code/support/findpkgs

If a _DEV version of a pet is found before the main pet ignore it.
See issue #933

woof-code/support/findpkgs

---

woof-code/3builddistro-Z
woof-code/_00func

No need to re-download initrd_progs every time merge2out is run.
Only tested in an arm build, but I still get an initrd.gz in
sandbox3/build

Move initrd-progs/0sources to local-repositories

---

initrd-progs/pkg/w_apps_static/w_apps/Makefile
initrd-progs/pkg/w_apps_static/w_apps/findpkgs-dep-helper.c
initrd-progs/pkg/w_apps_static/w_apps_static.petbuild
woof-code/support/findpkgs

A compiled helper program to speed up the dependency checking in
woof-CE/woof-code/support/findpkgs
There is support for --pkg-name-aliases="$PKG_NAME_ALIASES"
but using $PKG_NAME_ALIASES might cause unexpected problems

Add findpkgs-dep-helper.c

---

initrd-progs/pkg/w_apps_static/w_apps/findpkgs-dep-helper.c

Only check for existence of pkg_version when examining version of
potential dependency

findpkgs-dep-helper.c - Make pkg_version optional

---

woof-code/rootfs-skeleton/usr/lib/gtkdialog/box_splash

Help switches need to work when there isn't another parameter.
Border default of false did not work properly.

Fix help and border in box_splash

---

woof-distro/x86/ubuntu/xenial/DISTRO_PKGS_SPECS-ubuntu-xenial
woof-distro/x86/ubuntu/xenial/Packages-puppy-xenial-official

Apparently this cannot be found in 32-bit builds because it doesn't exist
http://www.murga-linux.com/puppy/viewtopic.php?p=918353#918353
http://packages.ubuntu.com/search?arch=any&searchon=names&keywords=libtsan

remove libtsan0 from x86 xenialpup?

---

woof-code/packages-templates/llvm-cut/FIXUPHACK

llvm-3.9.1-i586-1.txz has new components that Puppy does not require

llvm-cut FIXUPHACK

---

woof-distro/arm/raspbian/stretch/DISTRO_PKGS_SPECS-raspbian-stretch
woof-distro/arm/raspbian/stretch/DISTRO_SPECS
woof-distro/arm/raspbian/stretch/_00build.conf

- Add cifs-utils, mounting samba shares now works.
- Add nbd-client to devx, I use this for network swap
when making pets xz needs more RAM than a pi1 has.
- Changed SFSCOMP to arm instead of x86.
- Update a few missing dependencies.

Update raspbian/stretch to 7.0.2

---

woof-distro/x86/devuan/ascii/DISTRO_SPECS

Since there is already a puduan-6.0.0 with jessie in the wild, and dpup-stretch is on 7 too, and this spec has been updated a lot since 6 too, I think it makes sense?

Update Devuan to 7

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

Things seem to work better (but still a few terminal warnings) without debian version of glib. Thanks to pemasu
http://murga-linux.com/puppy/viewtopic.php?p=946215#946215

glib and zzz_glib conflict

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

"xdg_puppy" downloads:
http://distro.ibiblio.org/puppylinux/pet_packages-common/xdg_puppy-0.7.6-15-binaries_no-JWM-p4.pet
"xdg_puppy_jwm" downloads:
http://distro.ibiblio.org/puppylinux/pet_packages-common/xdg_puppy_jwm-0.7.6-16-i486.pet
2nd one has jwm-xdgmenu (needed for fixmenus by default), so I changed to xdg_puppy_jwm.
1st has fvwm-xdgmenu, icewm-xdgmenu and wm-xdgmenu only. Should that be kept too? :D

add jwm-xdgmenu for fixmenus

---

woof-code/rootfs-packages/wallpaper/usr/local/apps/Wallpaper/set_bg
woof-code/rootfs-skeleton/usr/sbin/set_bg

thr error was "No pinboard …was in use... the 'Default' pinboard has been selected. Use 'rox -p=Default' to turn it on in future." and caused two pinboards to be active at the same time!
feh --bg-scale $1 is a fix for conky transparency  to change on background changes

radkys fix for rox pinboard error and resulting mayhem.

---

ztools/patch-generator.sh

A patch file can be made by "dropping" a file from woof-out.../
onto patch-generator.sh in ROX as long as the file also exists in
woof-CE/woof-code

Add drag and drop support to ztools/patch-generator.sh

---

woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit

The /dev/pts mount is the only one in rc.sysinit that relies on an entry in /etc/fstab. The change make this mount compatible with the other mounts in rc.sysinit. End result and behaviour is identical.

Change mount for /dev/pts

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

file-5.30 (devuan ascii) is working for me instead of file-5.03w5 (wary5) and recognizes more file types. It is ~140k larger squashed but I think the trade-off is OK, do you agree? :laughing:

devuan: fix +autopoint and use more recent "file"

---

woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns

The "signal quality" commits are redundant -- the last can be ignored/rejected.
Why is line 834:
'"`/usr/lib/gtkdialog/xml_pixmap dialog-complete.svg popup`"'
while line 979 is:
'"`/usr/lib/gtkdialog/xml_pixmap dialog-complete popup`"' ?
They both appear to be treated the same way by /usr/lib/gtkdialog/xml_pixmap.  And none of the other "dialog-" files have the .svg.  What is that all about?

sns: sort wireless network display, fix icon name

---

woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns

There is this problematic wifi name in my neighbourhood that is 96 CHARACTERS LONG ( :laughing: ) and whenever sns finds it you need to expand to full window or scroll over to see the rest of the fields. Putting a limit of 20 on to the display seems to show all other names without the issue and gives enough room to add short quality 68/70 field back later.
Before:
https://ibb.co/fpNHAv
After:
https://ibb.co/bVJqVv

sns: Do not overflow the display

---

woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns

This number is handy to see, and doesn't hurt anything I think. I remove the word "Strength" because it is what took up most of the room. The MAC address can still be seen by scrolling over :)
Screenshot:
https://ibb.co/b4YSca

sns: Re-add signal strength number (short version)

---

woof-code/rootfs-skeleton/usr/sbin/pmount

Find which partition is mounted on / by looking in /proc/cmdline

Fix pmount root dev detection for Raspberry Pi

---

woof-code/rootfs-packages/getflash/pet.specs
woof-code/rootfs-packages/getflash/usr/sbin/getflash

I thought it was a bit strange that my woof-installed-packages still said 1.5-8 :laughing:

Update getflash pet.specs

---

woof-code/3builddistro-Z

I think if the user creates rootfs-packages.conf, they don't have to see the message again and need to press Enter on it to continue.

explain rootfs-packages.conf only if doesn't exist

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

having just the woof-ce version seems to be working so far in my tests, so I don't think the pet is needed any more?

slacko 14.0 - use woof-ce sfs_load

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

This one seems to work ok without the pet too. Sound works and I try the "Test Sound" and "Report" button with no issues

slacko 14.0 - use woof-ce mscw

---

woof-code/rootfs-packages/getflash/root/.getflash/getflash-conf

sourceforge has confusing wrappings of urls to go through to reach the target download url and if any url along the chain breaks the download fails
https://ibb.co/jrhevv
The old ibiblio link to Flash 10 still works (in Slacko 5.7 too). I think it is a better solution so you have multiple avenues to success instead of relying on messy sourceforge for both 11.2 and 10.3 :laughing:

Flash 10.3.183.90 - use ibiblio pet

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

defaults-chooser seems to be an older version of puppyapps default chooser that is now part of woof-CE skeleton. I think the puppyapps one is working ok now, I test changing geany to leafpad as default text editor and it worked, so older pet looks like "extra duplicate" menu entry (it can still be found in PPM if needed)

slacko 14.0 - woof-CE defaults chooser

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

This needs policykit/libpolkit to run without error, which seems large to add. Better to not have non-working entry in the menu and let PPM sort out dependencies if the user wants it I think?
https://ibb.co/fwhDxk

devuan devx: don't include sysprof by default

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

The file-5.03-w5.pet show newer sfs dates and blocksize with random values (file created in 1907, 1934... blocksize 1...). The slackware 14.0 one (file-5.11) shows them correctly
I don't know why puppy version was used originally, the 14.1 and 14.2 uses slackware version too.

slacko 14.0: try slackware "file"

---

kernel-kit/build.conf

I think just letting it use default is safer (xz is now default in 4.3 I think), as mksquashfs 3.3 and 4.0 fail to create sfs and tar.bz2 kernel package properly when -comp xz parameter is there (and you don't find this out until the very end :laughing: )

kernel-kit: default mksquashfs compression

---

woof-code/rootfs-skeleton/usr/local/petget/configure.sh
woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh

If the 'tmpfs' is too small a message is splashed to suggest a possible solution of creating some swap space, or continue using the pupsave (not recommended).

make 'tmpfs' default for petget in pupmode 13

---

woof-code/packages-templates/mozilla-seamonkey/FIXUPHACK

cd usr/lib/seamonkey* got confused and failed to cd for me then made 105MB omni.ja of all seamonkey in packages-slacko folder instead (and 18MB omni.ja was untouched) :laughing: changing it to cd ${SM} fixed
Screenshot: https://ibb.co/fwQ1Za

faster seamonkey edit

---

woof-distro/x86/slackware/14.2/DISTRO_PKGS_SPECS-slackware-14.2
woof-distro/x86_64/slackware64/14.2/DISTRO_PKGS_SPECS-slackware64-14.2

It looks like this 65kb txz is needed for the svn binaries in the devx.
svn: error while loading shared libraries: libserf-1.so.1: cannot open shared object file: No such file or directory
/usr/bin/svn
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
/usr/bin/svnbench
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
/usr/bin/svnmucc
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
/usr/bin/svnrdump
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not found
/usr/bin/svnsync
libserf-1.so.1 => not found
libserf-1.so.1 => not found
libserf-1.so.1 => not …

slacko 14.2: add libserf (to devx only)

---

woof-code/rootfs-skeleton/etc/rc.d/rc.network_eth
woof-code/rootfs-skeleton/usr/local/apps/Connect/AppRun
woof-code/rootfs-skeleton/usr/sbin/network_default_connect
woof-code/rootfs-skeleton/usr/sbin/networkdisconnect

Completes separation of netwiz from skeleton without impact.  The netwiz package can now be safely omitted from a distro.

network_connect: replace connect/disconnect netwiz dependency 

---

merge2out

If running woof-CE in a multi-user environment using run_woof
it is possible that the woof-CE repo has been cloned
as an ordinary user.

merge2out: make sure woof-out is owned by root

---

woof-distro/x86/ubuntu/xenial/DISTRO_PKGS_SPECS-ubuntu-xenial
woof-distro/x86_64/ubuntu/xenial64/DISTRO_PKGS_SPECS-ubuntu-xenial

Some ubuntu repo dependencies have changed when I build this with latest woof-CE.
Before spec update: http://txt.do/d62gs
After spec update: http://txt.do/d62ga

xenial64: update for new missing deps

---

woof-distro/x86/slackware/14.0/Packages-puppy-slacko14-official

The 2015 version in noarch list is not compatible with this jwm's autohide syntax so nothing happens when you try to use autohide option. This one (also used in slacko 5.7) works

slacko 14.0: fix autohide (use jwmconfig3-2014)

---

woof-code/support/findpkgs

If FALLBACKS_COMPAT_VERSIONS did not list DISTRO_COMPAT_VERSION
it would end up set to FALLBACKS_COMPAT_VERSIONS=''
If you want the original behavior just set
FALLBACKS_COMPAT_VERSIONS=''

support/findpkgs - Fix for FALLBACKS_COMPAT_VERSIONS

---

woof-code/rootfs-packages/redshiftgui_wrapper/pet.specs
woof-code/rootfs-packages/redshiftgui_wrapper/pinstall.sh
woof-code/rootfs-packages/redshiftgui_wrapper/root/Startup/redshiftgui_tray
woof-code/rootfs-packages/redshiftgui_wrapper/usr/bin/redshiftgui.sh

This supports automatic execution of RedshiftGUI, if present, to adjust display color for nighttime.  It does nothing if RedshiftGUI is not installed or has not been given the user's location, which determines the times of day/night transition.

redshiftgui_wrapper: add wrapper and auto startup for RedshiftGUI

---

woof-code/_00func

This way they will not be deleted if you delete your woof-out_*

_00func: link kernel-kit/sources and tools to local-repositories

---

woof-distro/x86/slackware/14.0/_00build.conf

I notice this option when looking at mrfricks xenialpup commits, seems like a great idea, which makes easier to fix some things. I started with these:
1. Some programs/libraries have dependencies that are not met, sometimes because lib is wrong version, the biggest offender probably being the 1.2MB x264 binary: http://murga-linux.com/puppy/viewtopic.php?p=976194#976194
2. Pmusic is already part of OpenWith from the PMUSIC_TRAY pet, this deletes duplicate OpenWith entry, and adds one for gnome-mplayer
3. Some programs (xarchive) look for 7za instead of 7z, and will not open 7z archive without finding it. Also added an icon for 7z files so it doesn't show up as unknown
4. the e3 binary can't be stripped or you get "segmentation error", this was fixed then removed from woof-CE so I bring it …

slacko 14.0 - _00build.conf with extra commands

---

woof-code/rootfs-skeleton/usr/sbin/shutdownconfig

**Fix for issue:**
https://github.com/puppylinux-woof-CE/woof-CE/issues/1115
**Rootcause:** 
In shutdownconfig, there is a if check to verify valid partitions. In  that check, nvme* is not added, hence even if we select a valid  partition with available space, not able to proceed.
**Fix:**
Added the nvme* in the 'if' check

Added support for nvme ssd drives for puppy-save files

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

puduan is now in-sync with stretch and uses libprocps6
> Puduan-7.0.0b1
> Start: Fri Jan  5 06:42:42 EST 2018
> * Checking system dirs: /bin /usr/libexec /sbin /usr/bin /usr/sbin /usr/games /usr/local/bin
> 
> /bin/ps-FULL
> 	libprocps.so.6 => not found
> 		libprocps.so.6 (LIBPROCPS_0) => not found
> 
> /sbin/sysctl
> 	libprocps.so.6 => not found

puduan: use libprocps6

---

woof-distro/x86/debian/stretch/_00build.conf
woof-distro/x86/devuan/ascii/_00build.conf

Someone here (gyro maybe?) said UEFI compatibility should be there by default. It adds about 4MB (1-2%) to the size of the iso I think. I don't have UEFI machine but I think this makes sense. Do you agree? :)

dpup: Add UEFI support by default

---

merge2out

If woof-distro/.../rootfs-skeleton/ contained only links and
directories but no regular files it was ignored.

merge2out: rootfs-skeleton bug fix

---

woof-code/packages-templates/alsa-lib_FIXUPHACK

alsa-lib from Slackware puts unwanted /etc/asound.conf into the devx and this kills aplay.

Remove unwanted asound.conf from devx

---

woof-code/support/findpkgs

Some Packages-puppy-*-official package lists have pets marked as
noarch, even though they are not noarch.  @peabee asked for this.

findpkgs: Increase priority of common32/64

---

woof-distro/x86/slackware/14.0/Packages-puppy-slacko14-official

These 3 work better from 14.0 version (noarch updates_mgr-0.21 does not work at all in it, maybe in 14.1 too)
https://github.com/puppylinux-woof-CE/woof-CE/issues/1133#issuecomment-377586760
The others I did not test fully but are maybe ok/good. Loading devx then making a savefile appeared to load the SFS on next bootup but really didn't too, perhaps a different sfs_load is needed or it was a strange one-off thing :laughing:

14.0 - Partially revert "noarch pet merge"

---

woof-distro/x86/slackware/14.0/_00build.conf

There seems to be two entries in right-click OpenWith list that point to the same place
Screenshot: https://ibb.co/cQHmcH

slacko 14.0 - remove duplicate FFConvert in OpenWith

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

This one seems to work better (even better than in Slacko 5.7, which went through suspend cycle twice when closed the lid on laptop) and is used in other puppies. For full acpid you can install acpid-2.0.16 (slackware) from ppm, errors with acpid-1.0.10-slacko in woof-CE first reported here: http://murga-linux.com/puppy/viewtopic.php?p=989113#989113

slacko 14.0 - update acpid to noarch

---

woof-distro/x86/slackware/14.0/Packages-puppy-slacko14-official

With Packages-puppy-slacko-official removed (https://github.com/puppylinux-woof-CE/woof-CE/commit/9e76ea3f89e6a4871748847913cab6b3cffb3364) woof-CE picks inkscapelite-0.36.3-no_gnomeprint-q1.pet from puppy-common which works almost as good as slacko one that was grabbed before but seems to complains about this: 
/usr/bin/inkscapelite
libpopt.so.0 (LIBPOPT_0) => not found
Both pets still have redrawing rulers bug (patched in slacko 6.3.2 and 7) though I think regular slacko inkscapelite-0.36.3-i486 seems slightly better to use than common due to not warning about missing lib. Thoughts? :)
edit: I found fixed inkscapelite-0.36.3_patched-glib-rulers.tar.xz source if it makes more sense to upload an "improved" pet instead of either option http://distro.ibiblio.org/puppylinux/sources/i/

slacko 14.0 - inkscapelite slacko->slacko14

---

woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii

This doesn't really work, because of missing libnetpbm10:
/usr/bin/giftopnm
libnetpbm.so.10 => not found
/usr/bin/jpegtopnm
libnetpbm.so.10 => not found
/usr/bin/pamcut
libnetpbm.so.10 => not found
/usr/bin/pamdice
libnetpbm.so.10 => not found
/usr/bin/pamfile
libnetpbm.so.10 => not found
/usr/bin/pamstretch
libnetpbm.so.10 => not found
/usr/bin/pbmtext
libnetpbm.so.10 => not found
/usr/bin/pbmtoxbm
libnetpbm.so.10 => not found
/usr/bin/pgmramp
libnetpbm.so.10 => not found
/usr/bin/pgmslice
libnetpbm.so.10 => not found
/usr/bin/pgmtopbm
libnetpbm.so.10 => not found
/usr/bin/pgmtoppm
libnetpbm.so.10 => not found
/usr/bin/pngtopnm
libnetpbm.so.10 => not found
/usr/bin/pnmalias
libnetpbm.so.10 => not found
/usr/bin/pnmcat
libnetpbm.so.10 => not found
/usr/bin/pnmcolormap
libnetpbm.so.10 => …

puduan: remove netpbm?

---

woof-code/rootfs-skeleton/usr/local/pup_event/frontend_funcs
woof-code/rootfs-skeleton/usr/local/pup_event/frontend_timeout

there is the freememapplet_tray app running in every pup
so you have an idea about storage usage.
if the icon turns red, it means the personal storage is getting full
frontend_timeout already runs a lot of apps every 6 seconds, including ps, grep
and cddetect_quick needed for an optical drv + systemd-udevd
greps /proc/mounts
this extra code is overkill
@gyrog has patches for these functions for his overlayfs stuff
if this is merged those patches are probably not needed anymore...
maybe these functions should be moved to somewhere else?

pup_event_frontend: remove free_func() and free_flash_func()

---

woof-distro/x86/slackware/14.2/DISTRO_PKGS_SPECS-slackware-14.2
woof-distro/x86_64/slackware64/14.2/DISTRO_PKGS_SPECS-slackware64-14.2

There seems to be some incompatibility with these new themes and jwm 2.3.2
https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-code/rootfs-packages/jwm_config/usr/share/jwm/themes
Using jwm 2.3.6 from slackware seems to fix it, and hasn't caused me any issues yet.
I added to master because I think it is a bug, is this a good idea? :cat2:

Slacko 14.2 - Switch to jwm 2.3.6

---

woof-distro/x86/slackware/14.0/Packages-puppy-slacko14-official

The ones in noarch are too new (program entries and urls) and only work with Slacko 632 and 700.

slacko 14.0 - bring back sfs_manager-0.8

---

woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown

When saving after a pfix=ram bootup, any files deleted before the initial save re-appear in the next bootup.  Whiteout and other hidden files are not saved.  Please hold this pull request if you know of a reason to not copy all hidden files.  This change seems consistent with saving in other pup-states.

rc.shutdown: saving after first boot, copy all puprw files, including hidden

---

woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0

This has been removed from noarch list
https://github.com/puppylinux-woof-CE/woof-CE/commit/fe2e50b85431e375293c2a9b1f4e13a0236a422e

no|desksetup

---

woof-code/rootfs-packages/firewall_ng/usr/sbin/firewall_ng
woof-code/rootfs-packages/frisbee/pet.specs
woof-code/rootfs-packages/simple_network_setup/etc/udev/rules.d/51-simple_network_setup.rules
woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns

The "no process killed" messages for splash messages are unneeded clutter in xerrs.log.
Also adds grep options to SNS rule and corrects frisbee version in pet.specs.

SNS, frisbee, firewall_ng: suppress error messages from kills of splash processes

---

woof-distro/x86/ubuntu/Packages-puppy-tahr-official

now in common32
if not removed this entry takes precedent over the common32 entry even if tahr should have less precedent in pet-repos list
if this cannot be removed - common32 needs to be amended

remove apulse

---

woof-code/rootfs-skeleton/usr/local/petget/pkg_chooser.sh

Package Manager sometimes claims it is already running, although it isn't.  This often happens the first time it is run in a session, but also occurs randomly.  The old 'pidof' line sometimes finds three PIDs instead of two.

pkg_chooser.sh: Correct 'running' check to avoid false positives

---

woof-code/rootfs-packages/network_wizard/pet.specs
woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/net-setup.sh
woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/rc.network
woof-code/rootfs-packages/simple_network_setup/pet.specs
woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/rc.network
woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns
woof-code/rootfs-skeleton/etc/rc.d/rc.network_eth

Received a report of ethernet connection failures apparently due to ethtool not responding within the 5 seconds allowed.  Wait increased to 8 seconds max.

network_connect: increase wait for ethtool in rc.network_eth, SNS & netwiz

---

woof-code/rootfs-packages/rox_config/usr/local/bin/rox

Rox is perfectly capable of handling URIs, with the -U switch.  Someone either didn't know about this switch, or wanted to make it work without the switch.  But they actually broke URI handling, because a file URI isn't just a file path with file:// prefixed - e.g. spaces are converted to "%20"
See www.murga-linux.com/puppy/viewtopic.php?t=115381 to see the sort of chaos this has caused (TLDR = bug ticket erroneously filed against another project and a bunch of people's time wasted).

Unbreak rox uri handling

---

initrd-progs/0initrd/init
woof-code/rootfs-skeleton/bin/plogin
woof-code/rootfs-skeleton/etc/rc.d/functions_x
woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown
woof-code/rootfs-skeleton/etc/rc.d/rc.sysinit
woof-code/rootfs-skeleton/etc/rc.d/rc.update
woof-code/rootfs-skeleton/usr/local/petget/configure.sh
woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
woof-code/rootfs-skeleton/usr/local/petget/removepreview.sh
woof-code/rootfs-skeleton/usr/local/pup_event/pup_event_timeout60
woof-code/rootfs-skeleton/usr/sbin/download_file
woof-code/rootfs-skeleton/usr/sbin/eventmanager
woof-code/rootfs-skeleton/usr/sbin/pupsave-backup
woof-code/rootfs-skeleton/usr/sbin/save2flash
woof-code/rootfs-skeleton/usr/sbin/sfs_load
woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy

This completely removes support for savepartitions. However init can identify savepartitions
and will show a "devastating" info msg (see commit diff)
The fact that savepartitions are only supported in PDEV1 makes them even less appealing.,,
This also shows basically all the core scripts that deal with pupmodes, so gyrog might want to take a look
patch
[remove-support-for-pupmodes-6-7.patch.zip](https://github.com/puppylinux-woof-CE/woof-CE/files/2887690/remove-support-for-pupmodes-6-7.patch.zip)
ref https://github.com/puppylinux-woof-CE/woof-CE/issues/1331#issuecomment-465622873
closes #1331
does anybody object this change?

remove support for PUPMODES 6 7

---

woof-code/rootfs-packages/network_wizard/pet.specs
woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/net-setup.sh
woof-code/rootfs-packages/simple_network_setup/pet.specs
woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns
woof-code/rootfs-skeleton/usr/sbin/connectwizard_exec
woof-code/rootfs-skeleton/usr/sbin/connectwizard_wrapper

SNS & network wizard identify themselves as the current network manager only if some action is taken, allowing the user to view the main windows without changing the manager used to reconnect at boot-up.
In NW, working with drivers also avoids setting NW as current.
SNS reports if it detects an active connection started by another network manager, advising disconnecting and reconnecting to put SNS in control.  In that situation, clicking "Disconnect Now" will re-display the main window to allow re-connection.

SNS 2.2.1, NW 2.1.1, connectwizard: bugfixes + avoid exec change on exit/X

---

woof-code/rootfs-skeleton/usr/bin/gcolor2

When I opened gcolor2 in the menu, I saw in the title "fallback if binary is missing". I think this might confuse the user and make them think "oh no, my binary is missing and I need to find it again" when the script is now the main gcolor2. The script seems to be working just as good as the original app so I think this message in brackets can be removed, or at least changed to something other than what it was before. Do you agree? :D

remove "fallback if binary is missing" message

---

initrd-progs/0initrd/init

Need to hide some init scripts due to puppy's rc.services nature that executes scripts in init.d with executable permissions. Also some autostarts which was not compatible with puppy

Improve underdog: hide some underdog init scripts and autostarts

---

woof-code/rootfs-skeleton/etc/rc.d/rc.shutdown

Remove whiteout files that hides underdog init scripts upon shutdown to avoid troubles

Remove whiteout files for mounted underdog

---

woof-distro/arm/raspbian/stretch/rootfs-skeleton/boot/bootmenu.txt

I ran into the “savefile massacre” bug when I was developing the init bootmenu script and never finished writing documentation for it.
On my SD card I put a copy of the DISTRO_SPECS file, the devx, puppy sfs and savefile in a directory named raspup-7.1 and use the following in my bootmenu.txt
```
LABEL raspup-7.1
PMEDIA usbflash
DISTRO_SPECS mmcblk0p1:/raspup-7.1/DISTRO_SPECS
PUPSFS mmcblk0p1:/raspup-7.1/puppy_raspup_7.1.sfs
PSAVE mmcblk0p1:/raspup-7.1/raspupsave.2fs
LABEL "raspup-7.1 pfix-ram"
DISTRO_SPECS mmcblk0p1:/raspup-7.1/DISTRO_SPECS
PFIX ram
LABEL search
SEARCH_DRIVE all
LABEL "ram disk shell"
PFIX rdsh
```
The boot loader/firmware has to be in the root of the SD card, as well as the kernels and kernel module sfs files.  But it is possible to choose between multiple Raspup …

woof-distro raspbian: Add bootmenu.txt

---

woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh

Sometimes list of files of an installed package (for example foo.files) produce this output like this
```
/
/.
./
./usr/bin/foo
usr/local/bin/foo
```
So it will be corrected like this
```
/usr/bin/foo
/usr/local/bin/foo
```

Correcting paths for saving lists of files

---

woof-code/rootfs-skeleton/usr/sbin/filemnt

Moving mounted image from /mnt to /media will shows the mounted disk image on file managers like Thunar and PCManFM for easy unmounting. Also pup-volume-monitor supports detection of mountpoints in /media.

filemnt: Move image file mountpoint from /mnt to /media

---

woof-distro/x86/debian/sid/repo-url
woof-distro/x86/devuan/ascii/repo-url
woof-distro/x86/ubuntu/trusty/repo-url

Uploaded appropriate packages to https://distro.ibiblio.org/puppylinux/next/ and tested all `i386` builds and debian `amd64` build. All boot to working desktop in qemu.

Update new 'puppy' URLs for deb based distros

---

woof-code/rootfs-skeleton/usr/sbin/shutdownconfig

Instead of flashy countdown timer shown, just a progress bar that indicates countdown
based from shinobar's shutdown save session interface

shutdownconfig: Improved shutdownconfig dialog

---

woof-code/rootfs-skeleton/bin/mount

Rather than dump ntfs error messages on /tmp just put it in a folder for easy troubleshooting

mount: contain ntfs error logs in a folder

---

woof-code/rootfs-skeleton/usr/sbin/alsaequal.sh
woof-code/rootfs-skeleton/usr/sbin/mscw2

mscw2 is the fatdog-default-soundcard taken from Fatdog64 803. In addition to selecting the active soundcard, it also has options to enable/disable the sample rate converter, equaliser, software volume control, pre-amp, swapping stereo channel, downmixing, and enabling mixout (record what you hear).
A companion script is included as well: alsaequal.sh, which enables control of the equaliser (when equaliser is enabled on mscw2). While mscw2 is a GUI application, alsaequal.sh is a terminal app.
The look and feel isn't the best since I use Xdialog, but it is fully packed in terms of functionality. Screenshots attached.

mscw2 and alsaequal.sh - taken from Fatdog64
