puppylinux-woof-CE/woof-CE

- woof-code/rootfs-skeleton/usr/sbin/sfsget
> added gui patch to accommodate any number of sfsbuttons in the screen of sfsget 

- woof-code/rootfs-skeleton/usr/sbin/filemnt
fix not mounting pure UDF iso images
> fix not mounting UDF iso images

- woof-code/packages-templates/libxcb_base/FIXUPHACK
- woof-code/rootfs-skeleton/etc/xdg/templates/_root_.jwmrc
i thought these two would come through individually but it seems you get the commits together, so i'll wait before doing anymore pull requests
> templates missing for xcb-sync and xcb-present, needed for 3d graphics

- woof-code/boot/initrd-tree0/init
- woof-code/huge_extras/init
I found some "if" statements that need quoting, so I quoted some "rm" statements as well.
> savefolder - cleanup - quoted some more variables

- woof-distro/x86_64/ubuntu64/trusty64/DISTRO_PKGS_SPECS-ubuntu-trusty
if this doesn't work i'm going back to bed!
> fix for spelling mistake in DISTRO_PKG_SPECS

- woof-code/rootfs-skeleton/usr/sbin/fontmanager
larger font sizes were requested in the tahrpup development thread for an older gentleman with poor eye sight
> add larger fontsizes for old eyes

- merge2out
- woof-code/0setup
this was discussed here https://github.com/puppylinux-woof-CE/woof-CE/issues/570
> 01mickos fix needed to build 64bit ubuntu pups

- woof-code/3builddistro
- woof-code/3builddistro-Z
the template might need updating as well to add mtpaints online documentation
> mtpaints help file was being stripped

- woof-code/rootfs-skeleton/usr/bin/pman
* I added support for groff [console and graphical environment], make default if available
* Workaround: depending on the program, pman may delete the generated html page before viewing,
see here [url]http://murga-linux.com/puppy/viewtopic.php?t=99634[/url]
* Various other edits
> /usr/bin/pman improvements

- woof-code/rootfs-skeleton/usr/bin/pet2tgz
- woof-code/rootfs-skeleton/usr/bin/tgz2pet
Comestic changes and a few more checks so you can use these scripts safely anywhere
The changes are in no way bash specific..
> pet2tgz and tgz2pet: cosmetics

- woof-distro/x86/ubuntu/Packages-puppy-tahr-official
- woof-distro/x86/ubuntu/trusty/DISTRO_PKGS_SPECS-ubuntu-trusty
- woof-distro/x86/ubuntu/trusty/DISTRO_SPECS
- woof-distro/x86_64/ubuntu/trusty64/DISTRO_PKGS_SPECS-ubuntu-trusty
- woof-distro/x86_64/ubuntu/trusty64/DISTRO_SPECS
> tahrpup 32 & 64bit recipe updates

- woof-distro/x86/ubuntu/trusty/DISTRO_PKGS_SPECS-ubuntu-trusty
- woof-distro/x86_64/ubuntu/trusty64/DISTRO_PKGS_SPECS-ubuntu-trusty
> remove truncate from tahrpups distro_pkg_specs

- woof-code/rootfs-skeleton/usr/sbin/fixmenus
http://murga-linux.com/puppy/viewtopic.php?p=877039#877039
> fixmenus: speed up

- woof-code/rootfs-skeleton/usr/sbin/indexgen.sh
http://murga-linux.com/puppy/viewtopic.php?p=877144#877144
> /usr/sbin/indexgen.sh: speed up

- woof-code/huge_extras/initmodules
This script is a GUI to write the config file for the "init insmod facility", (previously committed).
It's based on code "borrowed" from BootManager.
> initmodules - Configure init insmod facility

- woof-code/huge_extras/init
- woof-code/huge_extras/initmodules
Removes the "_" from the config filename so it is more like a savefile name.
> init insmod facility - change config filename

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
this fixes the issue i was having in precise
> puppyapps: make_box(): do not allow empty $DEFAULT_EXEC

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
puppyapps creates too many files in /tmp, now in /tmp/puppyapps
> puppyapps: use /tmp/puppyapps

- woof-code/rootfs-skeleton/usr/sbin/report-video
http://murga-linux.com/puppy/viewtopic.php?p=876879#876879
> report-video improvements

- README
- builders/build-iso.sh
- builders/deb-build.sh
- builders/deb2repo
- builders/installpkg
- builders/makedeb
- builders/makepkg
- builders/pkg2repo
- builders/removepkg
- builders/slack-build.sh
- woof-code/rootfs-skeleton/usr/bin/jwm_menu_create
- woof-distro/x86/debian/sid/repo-url
- woof-distro/x86/slackware/14.1/basesfs
- woof-distro/x86/slackware/14.1/repo-url
- woof-distro/x86/ubuntu/trusty/basesfs
- woof-distro/x86/ubuntu/trusty/repo-url
- woof-distro/x86_64/slackware/14.1/repo-url
Include latest changes for builders merged from upstream Fatdog-Like
> sync woof-next from woof-next-james

- woof-code/rootfs-skeleton/usr/local/bin/defaultaudiomixer
- woof-code/rootfs-skeleton/usr/local/bin/defaultaudioplayer
- woof-code/rootfs-skeleton/usr/local/bin/defaultbrowser
- woof-code/rootfs-skeleton/usr/local/bin/defaultcalendar
- woof-code/rootfs-skeleton/usr/local/bin/defaultchat
- woof-code/rootfs-skeleton/usr/local/bin/defaultchmviewer
- woof-code/rootfs-skeleton/usr/local/bin/defaultconnect
- woof-code/rootfs-skeleton/usr/local/bin/defaultcontact
- woof-code/rootfs-skeleton/usr/local/bin/defaultdraw
- woof-code/rootfs-skeleton/usr/local/bin/defaultemail
- woof-code/rootfs-skeleton/usr/local/bin/defaulthtmleditor
- woof-code/rootfs-skeleton/usr/local/bin/defaulthtmlviewer
- woof-code/rootfs-skeleton/usr/local/bin/defaultimageeditor
- woof-code/rootfs-skeleton/usr/local/bin/defaultimageviewer
- woof-code/rootfs-skeleton/usr/local/bin/defaultmediaplayer
- woof-code/rootfs-skeleton/usr/local/bin/defaultscreenshot
- woof-code/rootfs-skeleton/usr/local/bin/defaultspreadsheet
- woof-code/rootfs-skeleton/usr/local/bin/defaulttexteditor
- woof-code/rootfs-skeleton/usr/local/bin/defaulttextviewer
- woof-code/rootfs-skeleton/usr/local/bin/defaultwordprocessor
meanwhile puppyapps is perfected
besides puppyapps will be able to overwrite this anytime to take over the system
> revert to old values for the defaultapps

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
- misc edits to apps_array()
- new desktop_output() function
- call desktop_output() only when needed
- other insignificant edits..
> puppyapps: apps_array/search_desktop/misc adjustments

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
- misc edits to improve performance
- misc edits to the apps array
- window: execute.svg icon
- window: remove header/dog to make room [i can change it back but check it out first]
- -setdefs, option [this can be useful for testing purposes]
- $IGNORE_ALREADY_SET set by -setdefs and processed by get_default()
- move gui specific code down the command line code block
- possibly other changes not mentioned here
Sorry for cluttering all these changes.. i caught the flu
Now the gui looks ready, but I don't know to make it show up maximized so the user has a clear vision of all apps. Any ideas?
http://s11.postimg.org/k10a1urnl/capture25912.png
Maybe 2 or 3 apps are missing, two of them would be:
defaulttorrent
defaultpresentation [ms powerpoint-like apps]
> puppyapps: misc edits / gui code relocation / -setdefs option

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
puppyapps -sort 0..2
0 dont sort
1 sort by internal category name
2 sort by category description [default]
requested by mavrothal
> puppyapps: implement -sort option for the gui

- woof-code/rootfs-skeleton/usr/sbin/updatenetmoduleslist.sh
(original)
real    0m42.895s
user    0m8.993s
sys 0m20.629s
(mod)
real    0m7.683s
user    0m1.600s
sys 0m3.386s
> make updatenetmoduleslist.sh a bit faster

- woof-code/rootfs-skeleton/etc/init.d/10alsa
this does seem to work everytime
> 10alsa: initialize each soundcard individually

- woof-code/rootfs-packages/mscw/usr/bin/Multiple-Sound-Card-Wizard
To determine whether X is running.
> mscw: use $DISPLAY instead pidof X

- woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
by moeppyfan
http://murga-linux.com/puppy/viewtopic.php?t=105959
> SNS bugfix (hidden/blank/invalid wireless names)

- woof-code/rootfs-skeleton/etc/rc.d/rc.update
> rc.update: remove unused code

- woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
Code provided by JakeSFR IN #772
> SNS: ability to mask/unmask password

- woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
:neckbeard: sorry, but I am getting a bit interested in UI's of *gtkdialog* thought I might contribute a bit while learning it .. between where are the `primary-icon-name`s are stored ?? 
Hopefully everything is okay, I have tested them in puppy Linux - **tahrpup**
> Minor UI enhancements for sns

- woof-code/boot/initrd-tree0/init
These patches simply tidy the code, no functional change.
> Rationalise

- woof-code/rootfs-skeleton/usr/share/applications/jcontrol.desktop
Thanks, peabee, for bringing that to my attention,
> Remove redundant category "Utility" from jcontrol.desktop

- woof-code/rootfs-skeleton/usr/sbin/sfs_load
see http://murga-linux.com/puppy/viewtopic.php?p=816265#816265
> geoffreys fix for 'not enough space error' when.. sfs_get URL

- woof-code/rootfs-skeleton/usr/sbin/hostname-set
Is there any benefit to it? reverting fixes Rox bugs around since Slacko 5.7
http://www.murga-linux.com/puppy/viewtopic.php?p=906343#906343
http://www.murga-linux.com/puppy/viewtopic.php?p=908737#908737
> Revert hostname-set

- woof-code/rootfs-skeleton/usr/local/petget/removemodes.sh
Thanks to Abdorhman Ayman
http://www.murga-linux.com/puppy/viewtopic.php?t=108063
> Typo in PPM

- woof-code/rootfs-skeleton/usr/bin/dir2pet
> dir2pet: Add user control of compression default; align & edit help output

- woof-code/rootfs-packages/getflash/root/.getflash/getflash-conf
Courtesy of 01micko :laughing:
http://www.murga-linux.com/puppy/viewtopic.php?p=928449#928449
Might change again soon if Flash 23 npapi goes stable?
> "Darn Adobe at it again with their URL changes"

- woof-distro/Packages-puppy-noarch-official
> getflash-1.6

- woof-code/3builddistro-Z
- woof-distro/arm/raspbian/wheezy/DISTRO_COMPAT_REPOS-raspbian-wheezy
- woof-distro/arm/raspbian/wheezy/DISTRO_PKGS_SPECS-raspbian-wheezy
- woof-distro/arm/raspbian/wheezy/DISTRO_SPECS
Its not very polished, 3builddistro-Z will insist on downloading one of the "Huge_Kernel" pets, but it boots to desktop on both my pi1 and pi2.
I haven't done any x86 test build, and if you want to wait until one of your test builds I'm not in any hurry.  I saw the dates on some of my old commits and I haven't worked on this for almost a year.
> Raspberry Pi Build

- woof-code/rootfs-skeleton/usr/sbin/filemnt
> Open a mounted file in a new window

- woof-distro/arm/raspbian/jessie/DISTRO_COMPAT_REPOS-raspbian-jessie
- woof-distro/arm/raspbian/jessie/DISTRO_PET_REPOS
- woof-distro/arm/raspbian/jessie/DISTRO_PKGS_SPECS-raspbian-jessie
- woof-distro/arm/raspbian/jessie/DISTRO_SPECS
debdb2pupdb segfaults while processing Packages-raspbian-jessie-main but I was able to test the build by using a Packages-raspbian-jessie-main that I made in an earlier version of woof-CE
> Add support for Raspbian Jessie

- woof-distro/Packages-puppy-noarch-official
> New version Pup-SysInfo

- ztools/README.md
I'm not familiar with gitrepo, so my usage instructions are 
just a guess from reading the script, but it's a start.
> Update and rename patch-generator.sh.README to README.md

- woof-distro/arm/raspbian/stretch/DISTRO_COMPAT_REPOS-raspbian-stretch
- woof-distro/arm/raspbian/stretch/DISTRO_PET_REPOS
- woof-distro/arm/raspbian/stretch/DISTRO_PKGS_SPECS-raspbian-stretch
- woof-distro/arm/raspbian/stretch/DISTRO_SPECS
- woof-distro/arm/raspbian/stretch/Packages-raspbian-stretch-overrides
- woof-distro/arm/raspbian/stretch/packages-templates/ca-certificates/pinstall.sh
- woof-distro/arm/raspbian/stretch/packages-templates/firmware-brcm80211/lib/firmware/brcm/brcmfmac43430-sdio.txt
- woof-distro/arm/raspbian/stretch/packages-templates/linux-image-rpi/FIXUPHACK
- woof-distro/arm/raspbian/stretch/packages-templates/linux-image-rpi2/FIXUPHACK
- woof-distro/arm/raspbian/stretch/patches/multi-kernel-firmware.dep.patch
- woof-distro/arm/raspbian/stretch/patches/pkgs-overrides.patch
Raspbian stretch is still in testing, uses two debs from jessie,
listed in Packages-raspbian-stretch-overrides
- raspberrypi-bootloader-nokernel    jessie version is newer
- firmware-ralink   missing in stretch
This commit does not include changes I made to the file and openssl templates.
Would you prefer them as commits changing the templates in woof-CE or as extra templates in raspbian/stretch/packages-templates?
> Add raspbian/stretch 7.0.0

- woof-code/packages-templates/openssl/FIXUPHACK
If either of these are a problem I can put them in raspbian/stretch/packages-templates/ instead.
> Template changes

- woof-code/rootfs-packages/jwm_config/root/.jwm/backup/jwmrc-personal
- woof-code/rootfs-packages/jwm_config/root/.jwm/jwmrc-personal
I use this "windows refugees" shortcut sometimes to lock my laptop in public places, especially now as some newer Slacko pthemes don't have the lock icon on desktop any more.
> Super Key + L to lock computer?

- woof-distro/arm/raspbian/stretch/DISTRO_PKGS_SPECS-raspbian-stretch
- woof-distro/arm/raspbian/stretch/DISTRO_SPECS
Add some missing dependencies for devx.
> Update raspbian/stretch to 7.0.1

- woof-code/rootfs-packages/pfind/usr/local/pfind/pfindrc
change rox to defaultfilemanager
> Make pfind less rox reliant

- woof-code/rootfs-packages/getflash/pinstall.sh
- woof-code/rootfs-packages/getflash/root/.getflash/getflash-conf
- woof-code/rootfs-packages/getflash/root/Startup/getflash_auto
- woof-code/rootfs-packages/getflash/usr/sbin/getflash
This is the complete set of changes (6 commits).
> Update getflash to merge 1.5-8 and 1.6.1, with refinements

- woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii
Thanks to Billtoo
https://ibb.co/g4yoJv
http://ambrolla.mirror.devuan.org/devuan/pool/main/p/procps/
> Devuan procps binaries want libprocps4

- woof-code/3builddistro-Z
nice idea @mavrothal. I will test this later :D
> minor spelling fix

- woof-code/rootfs-skeleton/usr/sbin/puppyapps
thanks to shinobar
http://www.murga-linux.com/puppy/viewtopic.php?p=946892#946892
> changes made to puppyapps -> All did not save

- woof-code/rootfs-skeleton/usr/sbin/delayedrun
see: http://www.murga-linux.com/puppy/viewtopic.php?p=950257
> Startup fix

- woof-code/rootfs-skeleton/usr/sbin/delayedrun
> Startup fix #2

- woof-code/rootfs-skeleton/usr/local/simple_network_setup/sns
In STOCK=gtk (new default) this icon did not display (bug or feature? :laughing: )
https://ibb.co/hjyeWQ
> fix SNS "Successful connection" icon

- woof-code/rootfs-skeleton/usr/bin/dir2pet
...if the directory they typed does not exist
> dir2pet: give a more definite error message

- woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns
see
https://github.com/puppylinux-woof-CE/woof-CE/pull/1018#commitcomment-22311141
and here for an another idea that might work
https://github.com/puppylinux-woof-CE/woof-CE/pull/1019
> Remove the sort that doesn't work and breaks sns

- woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns
- woof-code/rootfs-skeleton/usr/share/pixmaps/puppy/wifi_encrypted.svg
- woof-code/rootfs-skeleton/usr/share/pixmaps/puppy/wifi_open.svg
thanks to 01micko
https://github.com/puppylinux-woof-CE/woof-CE/pull/1019#issuecomment-305018527
> sns: add and use new encryption icons

- woof-code/rootfs-packages/getflash/usr/sbin/getflash
Thanks to Geoffrey
http://www.murga-linux.com/puppy/viewtopic.php?p=956176#956176
> Update getflash grep -A2 to -A3

- woof-distro/x86/slackware/14.0/DISTRO_PKGS_SPECS-slackware-14.0
- woof-distro/x86/slackware/14.0/Packages-puppy-slacko14-official
all versions 2.2 - 2.7 gave me "Segmentation Error", this one worked and shows up on the tray :D
> slacko 14.0 - use freememapplet-2.8.6

- kernel-kit/configs_x86/DOTconfig-3.16.43-i686-4g
- kernel-kit/configs_x86_64/DOTconfig-3.16.43-x86_64
Reverts puppylinux-woof-CE/woof-CE#1038
> Revert "Update and rename DOTconfig-3.16.43-i686-4g to DOTconfig-3.16.44-i686-4g"

- woof-code/rootfs-skeleton/usr/bin/tgz2pet
Report by bug
http://www.murga-linux.com/puppy/viewtopic.php?t=110713
> Partially revert "tgz2pet: misc edits"

- woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii
My (maybe all?) laptop needed this for lid suspend to work
> devuan: add acpid-busibox

- woof-distro/x86/debian/stretch/DISTRO_PKGS_SPECS-debian-stretch
- woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii
> debian and devuan: --> to rootfs-packages

- woof-code/rootfs-skeleton/usr/sbin/filemnt
I think this works? Thanks to radky
http://www.murga-linux.com/puppy/viewtopic.php?p=958263#958263
> Fix #907 for Rox

- woof-code/rootfs-skeleton/usr/local/petget/check_deps.sh
- woof-code/rootfs-skeleton/usr/local/petget/configure.sh
It's working for me. Free free to test/improve
> ppm: Add option to skip scanning all files for missing dependencies

- woof-code/rootfs-skeleton/usr/sbin/wizardwizard
Before:
https://ibb.co/jeoYAF
After:
https://ibb.co/hGKUja
I think this blank space was filled with "Menu Manager" in the middle a long time ago (Slacko 5.3 or 5.5?).
> wizardwizard: re-add 9th entry if no pdesktop

- woof-code/3builddistro-Z
32 bit number no longer appended
> Remove redundant comment from DISTRO_SPECS

- woof-code/1download
Ready for a new multiple-package 2createpackages tool.
> Record packages downloaded

- woof-code/1download
Sorry - got it wrong....2nd attempt
> Correction

- woof-code/packages-templates/readline_FIXUPHACK
there is another possibility :laughing:
> slacko 14.0: make readline work again

- woof-code/rootfs-skeleton/usr/bin/xsaneshell
needed for wifi connected scanners
> add scan wifi option to xsaneshell

- kernel-kit/build.conf
- kernel-kit/build.sh
- kernel-kit/funcs.sh
- kernel-kit/pi-zero-build.conf
- kernel-kit/pi2-build.conf
Over the summer I got kernel-kit to cross compile kernels with AUFS for Raspberry Pi.
I finally made the changes into proper commits.
> Kernel kit changes

- initrd-progs/0initrd/init
- woof-code/3builddistro-Z
- woof-code/support/arm_zip_file.sh
- woof-code/support/kit_kernel.sh
- woof-distro/arm/raspbian/stretch/DISTRO_PKGS_SPECS-raspbian-stretch
- woof-distro/arm/raspbian/stretch/DISTRO_SPECS
- woof-distro/arm/raspbian/stretch/_00build.conf
- woof-distro/arm/raspbian/stretch/rootfs-skeleton/boot/config.txt
Apparently I can't reopen the old pull request after force pushing the changes.
Tested the modified init in my Pi build and in the initrd on my desktop, bootinit.log looks good.
> Zip file frugal install for Raspberry Pi

- woof-distro/x86/debian/stretch/DISTRO_PKGS_SPECS-debian-stretch
- woof-distro/x86/devuan/ascii/DISTRO_PKGS_SPECS-devuan-ascii
I think this got removed in last commit, it suspends laptop when lid is closed
> stretch and puduan: add acpid-busibox for suspend

- woof-distro/x86/debian/stretch/_00build.conf
- woof-distro/x86/devuan/ascii/_00build.conf
> stretch and puduan: fix some menu entries

- .gitignore
- merge2out
- merge2out-gui
- woof-code/_00func
Completed a modified xenial64 build and ran merge2out/0setup several times without noticing any problems.
> merge2out-gui

- woof-code/rootfs-skeleton/usr/sbin/run-as-spot
See:
http://murga-linux.com/puppy/viewtopic.php?p=982274#982274
> Fix for mozilla browsers run-as-spot under LXDE

- woof-code/packages-templates/glibc_locales/FIXUPHACK
> Add i18n_ctype

- woof-code/rootfs-packages/frisbee/usr/local/frisbee/func
> Stop Frisbee entries being corrupted

- woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic
> remove pupx .pet

- woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic
looks like was added as a separate package in artful
http://www.murga-linux.com/puppy/viewtopic.php?p=992169#992169
> add gtk-update-icon-cache

- woof-code/rootfs-skeleton/usr/sbin/remasterpup2
see:
http://www.murga-linux.com/puppy/viewtopic.php?p=992793
> Remaster - copy all *drv .sfs

- kernel-kit/configs_x86/DOTconfig-3.2.102-i686-4g
- kernel-kit/patches/aufs_sources/apply
- kernel-kit/patches/aufs_sources/k3.2.66.patch
Fiixes this compilation error: https://github.com/puppylinux-woof-CE/woof-CE/pull/1209
> add aufs patch: k3.2.66.patch

- woof-distro/x86/slackware/14.0/_00build.conf
broken again :laughing: https://github.com/puppylinux-woof-CE/woof-CE/pull/1168
> slacko 14.0 - fix duplicate FFConvert entry

- woof-distro/x86/Packages-puppy-common32-official
- woof-distro/x86_64/Packages-puppy-common64-official
> pmusic_PLUGIN_trayapp-0.5- common32 & common64

- woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic
pmusic_PLUGIN_trayapp from common32
> pmusic_PLUGIN_trayapp

- woof-code/rootfs-packages/pupdial/usr/local/pupdial/gen_modem_init_string
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/modemdisconnect
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/modemprobe
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/modemprobe_erase
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/modemprobe_help
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/modemtest
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/pupdial
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/pupdial_init_hotpluggable
- woof-code/rootfs-packages/pupdial/usr/local/pupdial/pupdial_wizard_helper
Create a package for pupdial and copy the current versions of its files to the package into a dedicated directory, as the basis for updates to pupdial 2.0.
> Seed new pupdial package directory with current file versions

- woof-distro/Packages-puppy-noarch-official
I declare Locator officially dead, googles grab for cash and world domination is to blame.
http://www.murga-linux.com/puppy/viewtopic.php?p=1005347#1005347
> Locator officially dead

- woof-code/rootfs-packages/network_wizard/pet.specs
- woof-code/rootfs-packages/network_wizard/pinstall.sh
- woof-code/rootfs-packages/network_wizard/usr/local/bin/net-setup.sh
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/ndiswrapperGUI.sh
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/net-setup.sh
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/rc.network
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/wag-profiles.sh
- woof-code/rootfs-skeleton/etc/rc.d/rc.network_eth
- woof-code/rootfs-skeleton/etc/rc.d/rc.network_pwf_stop
- woof-code/rootfs-skeleton/usr/local/apps/Connect/AppRun
- woof-code/rootfs-skeleton/usr/sbin/connectwizard
- woof-code/rootfs-skeleton/usr/sbin/connectwizard_2nd
- woof-code/rootfs-skeleton/usr/sbin/connectwizard_exec
- woof-code/rootfs-skeleton/usr/sbin/connectwizard_wrapper
- woof-code/rootfs-skeleton/usr/sbin/network_default_connect
- woof-code/rootfs-skeleton/usr/sbin/networkdisconnect
- woof-code/rootfs-skeleton/usr/share/doc/HOWTO_modem.htm
Connect wizard will offer peasywifi as a wireless option if installed, such that it co-exists with other tools without interference and allows switching between it and other network managers.
> Network connect: Move network wizard; add connect support for peasywifi

- woof-code/rootfs-packages/network_wizard/pet.specs
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/net-setup.sh
- woof-code/rootfs-packages/network_wizard/usr/local/network-wizard/rc.network
- woof-code/rootfs-packages/pupdial/pinstall.sh
- woof-code/rootfs-packages/simple_network_setup/pet.specs
- woof-code/rootfs-packages/simple_network_setup/pinstall.sh
- woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/rc.network
- woof-code/rootfs-packages/simple_network_setup/usr/local/simple_network_setup/sns
- woof-code/rootfs-packages/simple_network_setup/usr/sbin/sns
The SNS change filters iwconfig output to avoid processing unused lines, on the assumption that the data otherwise exceeds some internal limit on variable contents, reported here: 
"SNS and places with over 80-100 wifi signals"
http://www.murga-linux.com/puppy/viewtopic.php?p=996815#996815
There are no complaints, so I assume it helps.
> Network connect: Correct some details; increase SNS network capacity

- woof-code/rootfs-packages/pupdial/usr/local/pupdial/get_bluetooth_connection
requested by @rserwin1 
This seems to be preventing me from updating my testing branch in github since August.
Has this been done?  Or are you waiting for me to confirm my request?
> add 'get_bluetooth_connection' to 'pupdial' pkg template

- woof-code/rootfs-skeleton/usr/bin/wmexit
> Prepare for future

- woof-distro/Packages-puppy-noarch-official
- woof-distro/x86/ubuntu/upupbb/DISTRO_PKGS_SPECS-ubuntu-bionic
+ yes|gptfdisk||exe,doc,dev,nls for upupbb
> PupMates updates + 

- woof-code/rootfs-skeleton/usr/share/doc/index.html.top
> RIGHTVER is wrong

- woof-distro/x86/slackware/14.0/DISTRO_COMPAT_REPOS-slackware-14.0
Re: https://github.com/puppylinux-woof-CE/woof-CE/commit/f379b4fead999c971e3503fb8f89df14e8db4898
Reported by 6502coder: http://murga-linux.com/puppy/viewtopic.php?p=1014036#1014036
After edit screenshot: https://ibb.co/Sv0wsbX
> The name is shown in updates_mgr (maybe only 14.0)

- woof-distro/Packages-puppy-noarch-official
> pupmd5sum-1.7.pet

- woof-distro/x86/slackware/14.0/_00build.conf
these ones don't seem to be needed any more
> slacko 14.0 - remove some obsolete patches

- woof-code/rootfs-packages/change_kernels/usr/sbin/change_kernels
> button link to kernel repos

- woof-code/rootfs-skeleton/usr/sbin/shutdownconfig
- woof-distro/arm/raspbian/stretch/patches/init.patch
Closes #1147
If the "savefile massacre" #1335 bug has been fixed this should now be safe.
> Add bootmenu support for raspbian based builds

- woof-code/rootfs-skeleton/usr/local/petget/removepreview.sh
Process cache files after package removal
> removepreview: Process cache files after package removal

- woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
Process cache files and file association for xdg-compliant desktop environments
> installpkg.sh: Process cache files and file association for xdg-compliant desktop environments

- woof-code/rootfs-skeleton/usr/sbin/remove_builtin
Need to apply this routine in order to avoid troubles upon uninstallation of builtin packages
> Update cache files upon removal of builtin package

- woof-code/rootfs-skeleton/usr/sbin/sfs_load
Need cache file to be updated for more flawless integrations
> Update cache files during load and unload SFS modules

- woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
If there is an already installed package entry in the system database, just update the package files list and its database entry.
> Add replace package support for PPM

- woof-distro/arm/raspbian/README.md
How is this?
If you think I need to add some additional info, just give me a list of the topics and I’ll gladly write something up.
> woof-distro/arm/raspbian README.md

- woof-code/rootfs-skeleton/etc/rc.d/rc.update
Need to update cache file when underdog is mounted or unmounted
> Improve underdog linux support

- builders/devuan-build.sh
- setup.sh
- woof-distro/x86/devuan/ascii/basesfs
- woof-distro/x86/devuan/ascii/devx
- woof-distro/x86/devuan/ascii/repo-url
This is now tested to build a devuan-pup that boots to desktop.
No update on puppy scripts - still the same as 5 years ago.
> Add 32-bit devuan ascii build support

- woof-distro/x86_64/slackware/14.1/repo-url
> fix slackware64 puppy-specific repos

- woof-code/rootfs-skeleton/usr/sbin/pupautodetect
PupMTP is gui frontend for simple-mtpfs with multiple device support
http://www.murga-linux.com/puppy/viewtopic.php?p=1029394#1029394
> Add pupmtp to puppyautodetect

- woof-code/rootfs-skeleton/usr/sbin/snapmergepuppy
> Update snapmergepuppy: excluding /media folder

- woof-code/rootfs-skeleton/usr/local/petget/installpkg.sh
Dealing with package installing files at /media
> Update installpkg.sh: deal with /media folder

- woof-code/rootfs-skeleton/usr/sbin/remasterpup2
Always exclude /media folder and stay pristine upon remastering puppy
> Update remasterpup2: exclude /media folder

- woof-code/rootfs-skeleton/usr/sbin/pupcamera
Added multiple camera support (more than two cameras) even remote camera
> Rewritten pupcamera

- woof-code/rootfs-skeleton/usr/share/applications/filemnt.desktop
Add xdg compliant file association
> filemnt.desktop: Add mimetype assosciation

- builders/installpkg
- setup.sh
- woof-distro/x86/slackware/14.2/basesfs
- woof-distro/x86/slackware/14.2/devx
- woof-distro/x86/slackware/14.2/repo-url
- woof-distro/x86_64/slackware/14.2/basesfs
- woof-distro/x86_64/slackware/14.2/devx
- woof-distro/x86_64/slackware/14.2/repo-url
tested and have a working slackware64-14.2 distro connected by wirless and able to browse with firefox
> Next slacko patch

- woof-code/rootfs-skeleton/lib/dhcpcd/dhcpcd-hooks/99-notify
Try use notify send for announcing state changes otherwise rollback to gtkdialog-splash
> 99-notify: Use notify-send if installed
